#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


     #include "partcompute.h"
     #include "caterva.h" 
     # define CATERVA_MAXDIM 8



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // caterva_array *()(blosc2_cparams, blosc2_dparams, caterva_pparams)
/*  1 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // blosc2_cparams
/*  2 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // blosc2_dparams
/*  3 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // caterva_pparams
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // caterva_array *()(caterva_array *, caterva_array *)
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 31), // caterva_array *
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 35), // int()(caterva_array *)
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION, 35), // int()(caterva_array *, caterva_array *, size_t *, size_t *, size_t *)
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 15 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // size_t *
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 15),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 35), // int()(caterva_array *, void *)
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 21 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // void *
/* 22 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION, 35), // int()(void *, caterva_array *)
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 21),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_POINTER, 28), // blosc2_context *
/* 28 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // blosc2_context
/* 29 */ _CFFI_OP(_CFFI_OP_POINTER, 30), // blosc2_schunk *
/* 30 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // blosc2_schunk
/* 31 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // caterva_array
/* 32 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum $1
/* 33 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21), // int32_t
/* 34 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 23), // int64_t
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 37 */ _CFFI_OP(_CFFI_OP_ARRAY, 36), // size_t[8]
/* 38 */ (_cffi_opcode_t)(8),
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // uint8_t * *
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // uint8_t *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 43 */ _CFFI_OP(_CFFI_OP_ARRAY, 42), // uint8_t[5]
/* 44 */ (_cffi_opcode_t)(5),
/* 45 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_BLOSC_MAX_FILTERS(unsigned long long *o)
{
  int n = (BLOSC_MAX_FILTERS) <= 0;
  *o = (unsigned long long)((BLOSC_MAX_FILTERS) | 0);  /* check that BLOSC_MAX_FILTERS is an integer */
  return n;
}

static int _cffi_const_CATERVA_MAXDIM(unsigned long long *o)
{
  int n = (CATERVA_MAXDIM) <= 0;
  *o = (unsigned long long)((CATERVA_MAXDIM) | 0);  /* check that CATERVA_MAXDIM is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_blosc2_cparams(blosc2_cparams *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->compcode) | 0);  /* check that 'blosc2_cparams.compcode' is an integer */
  (void)((p->clevel) | 0);  /* check that 'blosc2_cparams.clevel' is an integer */
  (void)((p->use_dict) | 0);  /* check that 'blosc2_cparams.use_dict' is an integer */
  (void)((p->typesize) | 0);  /* check that 'blosc2_cparams.typesize' is an integer */
  (void)((p->nthreads) | 0);  /* check that 'blosc2_cparams.nthreads' is an integer */
  (void)((p->blocksize) | 0);  /* check that 'blosc2_cparams.blocksize' is an integer */
  { void * *tmp = &p->schunk; (void)tmp; }
  { uint8_t(*tmp)[5] = &p->filters; (void)tmp; }
  { uint8_t(*tmp)[5] = &p->filters_meta; (void)tmp; }
}
struct _cffi_align_typedef_blosc2_cparams { char x; blosc2_cparams y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_blosc2_dparams(blosc2_dparams *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->nthreads) | 0);  /* check that 'blosc2_dparams.nthreads' is an integer */
  { void * *tmp = &p->schunk; (void)tmp; }
}
struct _cffi_align_typedef_blosc2_dparams { char x; blosc2_dparams y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_blosc2_schunk(blosc2_schunk *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->version) | 0);  /* check that 'blosc2_schunk.version' is an integer */
  (void)((p->flags1) | 0);  /* check that 'blosc2_schunk.flags1' is an integer */
  (void)((p->flags2) | 0);  /* check that 'blosc2_schunk.flags2' is an integer */
  (void)((p->flags3) | 0);  /* check that 'blosc2_schunk.flags3' is an integer */
  (void)((p->compcode) | 0);  /* check that 'blosc2_schunk.compcode' is an integer */
  (void)((p->clevel) | 0);  /* check that 'blosc2_schunk.clevel' is an integer */
  (void)((p->typesize) | 0);  /* check that 'blosc2_schunk.typesize' is an integer */
  (void)((p->blocksize) | 0);  /* check that 'blosc2_schunk.blocksize' is an integer */
  (void)((p->chunksize) | 0);  /* check that 'blosc2_schunk.chunksize' is an integer */
  { uint8_t(*tmp)[5] = &p->filters; (void)tmp; }
  { uint8_t(*tmp)[5] = &p->filters_meta; (void)tmp; }
  (void)((p->nchunks) | 0);  /* check that 'blosc2_schunk.nchunks' is an integer */
  (void)((p->nbytes) | 0);  /* check that 'blosc2_schunk.nbytes' is an integer */
  (void)((p->cbytes) | 0);  /* check that 'blosc2_schunk.cbytes' is an integer */
  { uint8_t * *tmp = &p->filters_chunk; (void)tmp; }
  { uint8_t * *tmp = &p->codec_chunk; (void)tmp; }
  { uint8_t * *tmp = &p->metadata_chunk; (void)tmp; }
  { uint8_t * *tmp = &p->userdata_chunk; (void)tmp; }
  { uint8_t * * *tmp = &p->data; (void)tmp; }
  { blosc2_context * *tmp = &p->cctx; (void)tmp; }
  { blosc2_context * *tmp = &p->dctx; (void)tmp; }
  { uint8_t * *tmp = &p->reserved; (void)tmp; }
}
struct _cffi_align_typedef_blosc2_schunk { char x; blosc2_schunk y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_caterva_array(caterva_array *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { blosc2_schunk * *tmp = &p->sc; (void)tmp; }
  { size_t(*tmp)[8] = &p->shape; (void)tmp; }
  { size_t(*tmp)[8] = &p->cshape; (void)tmp; }
  { size_t(*tmp)[8] = &p->eshape; (void)tmp; }
  (void)((p->size) | 0);  /* check that 'caterva_array.size' is an integer */
  (void)((p->csize) | 0);  /* check that 'caterva_array.csize' is an integer */
  (void)((p->esize) | 0);  /* check that 'caterva_array.esize' is an integer */
  (void)((p->dim) | 0);  /* check that 'caterva_array.dim' is an integer */
}
struct _cffi_align_typedef_caterva_array { char x; caterva_array y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_caterva_pparams(caterva_pparams *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { size_t(*tmp)[8] = &p->shape; (void)tmp; }
  { size_t(*tmp)[8] = &p->cshape; (void)tmp; }
  (void)((p->dim) | 0);  /* check that 'caterva_pparams.dim' is an integer */
}
struct _cffi_align_typedef_caterva_pparams { char x; caterva_pparams y; };

static int _cffi_d_caterva_array_fill_from_schunk(caterva_array * x0, void * x1)
{
  return caterva_array_fill_from_schunk(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_caterva_array_fill_from_schunk(PyObject *self, PyObject *args)
{
  caterva_array * x0;
  void * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "caterva_array_fill_from_schunk", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(6), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(21), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (void *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(21), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = caterva_array_fill_from_schunk(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_caterva_array_fill_from_schunk _cffi_d_caterva_array_fill_from_schunk
#endif

static int _cffi_d_caterva_free_array(caterva_array * x0)
{
  return caterva_free_array(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_caterva_free_array(PyObject *self, PyObject *arg0)
{
  caterva_array * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(6), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = caterva_free_array(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_caterva_free_array _cffi_d_caterva_free_array
#endif

static int _cffi_d_caterva_get_slice(caterva_array * x0, caterva_array * x1, size_t * x2, size_t * x3, size_t * x4)
{
  return caterva_get_slice(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_caterva_get_slice(PyObject *self, PyObject *args)
{
  caterva_array * x0;
  caterva_array * x1;
  size_t * x2;
  size_t * x3;
  size_t * x4;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "caterva_get_slice", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(6), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(6), arg1) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (size_t *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(15), arg2) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (size_t *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(15), arg3) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(15), arg4, (char **)&x4);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x4 = (size_t *)alloca((size_t)datasize);
    memset((void *)x4, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x4, _cffi_type(15), arg4) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = caterva_get_slice(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_caterva_get_slice _cffi_d_caterva_get_slice
#endif

static caterva_array * _cffi_d_caterva_new_array(blosc2_cparams x0, blosc2_dparams x1, caterva_pparams x2)
{
  return caterva_new_array(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_caterva_new_array(PyObject *self, PyObject *args)
{
  blosc2_cparams x0;
  blosc2_dparams x1;
  caterva_pparams x2;
  caterva_array * result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "caterva_new_array", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x1, _cffi_type(2), arg1) < 0)
    return NULL;

  if (_cffi_to_c((char *)&x2, _cffi_type(3), arg2) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = caterva_new_array(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(6));
}
#else
static caterva_array * _cffi_f_caterva_new_array(blosc2_cparams *x0, blosc2_dparams *x1, caterva_pparams *x2)
{
  caterva_array * result;
  { result = caterva_new_array(*x0, *x1, *x2); }
  return result;
}
#endif

static int _cffi_d_caterva_schunk_fill_from_array(void * x0, caterva_array * x1)
{
  return caterva_schunk_fill_from_array(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_caterva_schunk_fill_from_array(PyObject *self, PyObject *args)
{
  void * x0;
  caterva_array * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "caterva_schunk_fill_from_array", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(21), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (void *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(21), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(6), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = caterva_schunk_fill_from_array(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_caterva_schunk_fill_from_array _cffi_d_caterva_schunk_fill_from_array
#endif

static caterva_array * _cffi_d_partcompute_schunk_mul(caterva_array * x0, caterva_array * x1)
{
  return partcompute_schunk_mul(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_partcompute_schunk_mul(PyObject *self, PyObject *args)
{
  caterva_array * x0;
  caterva_array * x1;
  Py_ssize_t datasize;
  caterva_array * result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "partcompute_schunk_mul", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(6), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (caterva_array *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(6), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = partcompute_schunk_mul(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(6));
}
#else
#  define _cffi_f_partcompute_schunk_mul _cffi_d_partcompute_schunk_mul
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "BLOSC_MAX_FILTERS", (void *)_cffi_const_BLOSC_MAX_FILTERS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CATERVA_MAXDIM", (void *)_cffi_const_CATERVA_MAXDIM, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "caterva_array_fill_from_schunk", (void *)_cffi_f_caterva_array_fill_from_schunk, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 19), (void *)_cffi_d_caterva_array_fill_from_schunk },
  { "caterva_free_array", (void *)_cffi_f_caterva_free_array, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 9), (void *)_cffi_d_caterva_free_array },
  { "caterva_get_slice", (void *)_cffi_f_caterva_get_slice, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 12), (void *)_cffi_d_caterva_get_slice },
  { "caterva_new_array", (void *)_cffi_f_caterva_new_array, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_caterva_new_array },
  { "caterva_schunk_fill_from_array", (void *)_cffi_f_caterva_schunk_fill_from_array, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 23), (void *)_cffi_d_caterva_schunk_fill_from_array },
  { "partcompute_schunk_mul", (void *)_cffi_f_partcompute_schunk_mul, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 5), (void *)_cffi_d_partcompute_schunk_mul },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "compcode", offsetof(blosc2_cparams, compcode),
                sizeof(((blosc2_cparams *)0)->compcode),
                _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "clevel", offsetof(blosc2_cparams, clevel),
              sizeof(((blosc2_cparams *)0)->clevel),
              _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "use_dict", offsetof(blosc2_cparams, use_dict),
                sizeof(((blosc2_cparams *)0)->use_dict),
                _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "typesize", offsetof(blosc2_cparams, typesize),
                sizeof(((blosc2_cparams *)0)->typesize),
                _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "nthreads", offsetof(blosc2_cparams, nthreads),
                sizeof(((blosc2_cparams *)0)->nthreads),
                _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "blocksize", offsetof(blosc2_cparams, blocksize),
                 sizeof(((blosc2_cparams *)0)->blocksize),
                 _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "schunk", offsetof(blosc2_cparams, schunk),
              sizeof(((blosc2_cparams *)0)->schunk),
              _CFFI_OP(_CFFI_OP_NOOP, 21) },
  { "filters", offsetof(blosc2_cparams, filters),
               sizeof(((blosc2_cparams *)0)->filters),
               _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "filters_meta", offsetof(blosc2_cparams, filters_meta),
                    sizeof(((blosc2_cparams *)0)->filters_meta),
                    _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "nthreads", offsetof(blosc2_dparams, nthreads),
                sizeof(((blosc2_dparams *)0)->nthreads),
                _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "schunk", offsetof(blosc2_dparams, schunk),
              sizeof(((blosc2_dparams *)0)->schunk),
              _CFFI_OP(_CFFI_OP_NOOP, 21) },
  { "version", offsetof(blosc2_schunk, version),
               sizeof(((blosc2_schunk *)0)->version),
               _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "flags1", offsetof(blosc2_schunk, flags1),
              sizeof(((blosc2_schunk *)0)->flags1),
              _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "flags2", offsetof(blosc2_schunk, flags2),
              sizeof(((blosc2_schunk *)0)->flags2),
              _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "flags3", offsetof(blosc2_schunk, flags3),
              sizeof(((blosc2_schunk *)0)->flags3),
              _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "compcode", offsetof(blosc2_schunk, compcode),
                sizeof(((blosc2_schunk *)0)->compcode),
                _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "clevel", offsetof(blosc2_schunk, clevel),
              sizeof(((blosc2_schunk *)0)->clevel),
              _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "typesize", offsetof(blosc2_schunk, typesize),
                sizeof(((blosc2_schunk *)0)->typesize),
                _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "blocksize", offsetof(blosc2_schunk, blocksize),
                 sizeof(((blosc2_schunk *)0)->blocksize),
                 _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "chunksize", offsetof(blosc2_schunk, chunksize),
                 sizeof(((blosc2_schunk *)0)->chunksize),
                 _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "filters", offsetof(blosc2_schunk, filters),
               sizeof(((blosc2_schunk *)0)->filters),
               _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "filters_meta", offsetof(blosc2_schunk, filters_meta),
                    sizeof(((blosc2_schunk *)0)->filters_meta),
                    _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "nchunks", offsetof(blosc2_schunk, nchunks),
               sizeof(((blosc2_schunk *)0)->nchunks),
               _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "nbytes", offsetof(blosc2_schunk, nbytes),
              sizeof(((blosc2_schunk *)0)->nbytes),
              _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "cbytes", offsetof(blosc2_schunk, cbytes),
              sizeof(((blosc2_schunk *)0)->cbytes),
              _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "filters_chunk", offsetof(blosc2_schunk, filters_chunk),
                     sizeof(((blosc2_schunk *)0)->filters_chunk),
                     _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "codec_chunk", offsetof(blosc2_schunk, codec_chunk),
                   sizeof(((blosc2_schunk *)0)->codec_chunk),
                   _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "metadata_chunk", offsetof(blosc2_schunk, metadata_chunk),
                      sizeof(((blosc2_schunk *)0)->metadata_chunk),
                      _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "userdata_chunk", offsetof(blosc2_schunk, userdata_chunk),
                      sizeof(((blosc2_schunk *)0)->userdata_chunk),
                      _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "data", offsetof(blosc2_schunk, data),
            sizeof(((blosc2_schunk *)0)->data),
            _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "cctx", offsetof(blosc2_schunk, cctx),
            sizeof(((blosc2_schunk *)0)->cctx),
            _CFFI_OP(_CFFI_OP_NOOP, 27) },
  { "dctx", offsetof(blosc2_schunk, dctx),
            sizeof(((blosc2_schunk *)0)->dctx),
            _CFFI_OP(_CFFI_OP_NOOP, 27) },
  { "reserved", offsetof(blosc2_schunk, reserved),
                sizeof(((blosc2_schunk *)0)->reserved),
                _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "sc", offsetof(caterva_array, sc),
          sizeof(((caterva_array *)0)->sc),
          _CFFI_OP(_CFFI_OP_NOOP, 29) },
  { "shape", offsetof(caterva_array, shape),
             sizeof(((caterva_array *)0)->shape),
             _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "cshape", offsetof(caterva_array, cshape),
              sizeof(((caterva_array *)0)->cshape),
              _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "eshape", offsetof(caterva_array, eshape),
              sizeof(((caterva_array *)0)->eshape),
              _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "size", offsetof(caterva_array, size),
            sizeof(((caterva_array *)0)->size),
            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "csize", offsetof(caterva_array, csize),
             sizeof(((caterva_array *)0)->csize),
             _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "esize", offsetof(caterva_array, esize),
             sizeof(((caterva_array *)0)->esize),
             _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "dim", offsetof(caterva_array, dim),
           sizeof(((caterva_array *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "shape", offsetof(caterva_pparams, shape),
             sizeof(((caterva_pparams *)0)->shape),
             _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "cshape", offsetof(caterva_pparams, cshape),
              sizeof(((caterva_pparams *)0)->cshape),
              _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "dim", offsetof(caterva_pparams, dim),
           sizeof(((caterva_pparams *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 36) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$blosc2_cparams", 1, _CFFI_F_CHECK_FIELDS,
    sizeof(blosc2_cparams), offsetof(struct _cffi_align_typedef_blosc2_cparams, y), 0, 9 },
  { "$blosc2_dparams", 2, _CFFI_F_CHECK_FIELDS,
    sizeof(blosc2_dparams), offsetof(struct _cffi_align_typedef_blosc2_dparams, y), 9, 2 },
  { "$blosc2_schunk", 30, _CFFI_F_CHECK_FIELDS,
    sizeof(blosc2_schunk), offsetof(struct _cffi_align_typedef_blosc2_schunk, y), 11, 22 },
  { "$caterva_array", 31, _CFFI_F_CHECK_FIELDS,
    sizeof(caterva_array), offsetof(struct _cffi_align_typedef_caterva_array, y), 33, 8 },
  { "$caterva_pparams", 3, _CFFI_F_CHECK_FIELDS,
    sizeof(caterva_pparams), offsetof(struct _cffi_align_typedef_caterva_pparams, y), 41, 3 },
  { "blosc2_context_s", 28, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$1", 32, _cffi_prim_int(4, 0),
    "BLOSC_MAX_FILTERS,CATERVA_MAXDIM" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "blosc2_context", 28 },
  { "blosc2_cparams", 1 },
  { "blosc2_dparams", 2 },
  { "blosc2_schunk", 30 },
  { "caterva_array", 31 },
  { "caterva_pparams", 3 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  8,  /* num_globals */
  6,  /* num_struct_unions */
  1,  /* num_enums */
  6,  /* num_typenames */
  NULL,  /* no includes */
  46,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_demo_(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_demo_(void) { return NULL; }
#  else
     initdemo_(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_demo_(void)
{
  return _cffi_init("demo_", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initdemo_(void)
{
  _cffi_init("demo_", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
